[workspace]
members = ["src/moonlink", "src/moonlink_backend", "src/moonlink_connectors"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "LicenseRef-BSL-1.1"

[workspace.dependencies]
arrow = { version = "55", default-features = false, features = ["canonical_extension_types"] }
arrow-array = "55"
arrow-schema = "55"
async-trait = "0.1"
bincode = "2"
chrono = { version = "0.4", default-features = false }
crc32fast = "1"
futures = { version = "0.3", default-features = false }
hashbrown = "0.15.3"
iceberg = { git = "https://github.com/apache/iceberg-rust.git", rev = "40b055a779365b121ad070b900389d27f8122741", default-features = false, features = [
  "storage-fs",
] }
itertools = { version = "0.14" }
multimap = { version = "0.10", default-features = false }
num-bigint = { version = "0.4" }
num-traits = "0.2"
opendal = { version = "0.53", default-features = false, features = [
  "services-s3",
] }
parquet = { version = "55", default-features = false, features = ["arrow", "async", "arrow_canonical_extension_types"] }
postgres-replication = { git = "https://github.com/Mooncake-labs/rust-postgres.git" }
roaring = "0.10"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1.45", default-features = false, features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
tokio-bitstream-io = "0.0.7"
tokio-postgres = { git = "https://github.com/Mooncake-labs/rust-postgres.git" }
url = "2.5"
uuid = { version = "1.16", default-features = false, features = ["v4"] }

[profile.release-with-debug]
inherits = "release"
debug = true
