[workspace]
members = [
    "src/moonlink",
    "src/moonlink_connectors",
    "src/moonlink_backend",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
async-trait = "0.1"
bincode = "2"

tokio-postgres = { git = "ssh://git@github.com/Mooncake-labs/rust-postgres.git"}
arrow = "54.2.1"
thiserror = "2.0.12"
parquet = "54.2.1"
tempfile = "3.18.0"
futures = "0.3.31"
multimap = "0.10.0"
chrono = "=0.4.39"
num-traits = "0.2.19"
postgres-replication = { git = "ssh://git@github.com/Mooncake-labs/rust-postgres.git" }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "sync", "time"] }
uuid = { version = "1.16.0", features = ["v4"] }
arrow-array = "54.2.1"
arrow-schema = "54.2.1"
serde_json = { version = "1.0", features = ["std"] }
iceberg = { git = "https://github.com/apache/iceberg-rust.git", rev = "b4bc6dd15ae4f7a4b1c9ce555e3458089a83e228" }
iceberg-catalog-rest = { git = "https://github.com/apache/iceberg-rust.git", rev = "b4bc6dd15ae4f7a4b1c9ce555e3458089a83e228" }
url = "2.5"
roaring = { version = "0.10.12", git = "https://github.com/RoaringBitmap/roaring-rs.git" }
crc32fast = "1.3"
opendal = { version = "0.53.1", features = ["services-s3"] }
bitstream-io = "3.2.0"
aws-sdk-s3 = "1.14.0"
tokio-retry = "0.3"

[profile.release-with-debug]
inherits = "release"
debug = true
