[workspace]
members = ["src/moonlink", "src/moonlink_backend", "src/moonlink_connectors"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
arrow = { version = "55", default-features = false }
arrow-array = "55"
arrow-schema = "55"
async-trait = "0.1"
bincode = "2"
bitstream-io = "4"
chrono = { version = "0.4", default-features = false }
crc32fast = "1"
futures = { version = "0.3", default-features = false }
hashbrown = "0.15.3"
iceberg = { git = "https://github.com/apache/iceberg-rust.git", rev = "111d0f3da525aad30335e211b5f29edd94c3ccf7", default-features = false, features = [
  "storage-fs",
] }
multimap = { version = "0.10", default-features = false }
num-traits = "0.2"
opendal = { version = "0.53", default-features = false, features = [
  "services-s3",
] }
parquet = { version = "55", default-features = false, features = ["arrow", "async"] }
postgres-replication = { git = "https://github.com/Mooncake-labs/rust-postgres.git" }
roaring = "0.10"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1.45", default-features = false, features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
tokio-bitstream-io = "0.0.7"
tokio-postgres = { git = "https://github.com/Mooncake-labs/rust-postgres.git" }
url = "2.5"
uuid = { version = "1.16", default-features = false, features = ["v4"] }

[profile.release-with-debug]
inherits = "release"
debug = true
